apiVersion: 1

datasources:
  # https://grafana.com/docs/grafana/latest/datasources/prometheus/
  - name: Prometheus
    type: prometheus
    uid: otel-metrics
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 10s
      exemplarTraceIdDestinations:
        - datasourceUid: otel-traces
          name: trace_id

        - url: http://jaeger:16686/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI

  # https://grafana.com/docs/grafana/latest/datasources/jaeger/
  - name: Jaeger
    type: jaeger
    uid: otel-traces
    url: http://jaeger:16686
    editable: true
    isDefault: false