apiVersion: 1

datasources:
  - name: Prometheus
    uid: otel-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: otel-traces
          name: trace_id

        - url: http://jaegerquery:16686/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI
