receivers:
  otlp:
    protocols:
      http:
      grpc:

  opencensus:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

processors:
  batch:

exporters:
  logging:
    verbosity: basic
  file/traces:
    path: /traces.json
  file/metrics:
    path: /metrics.json
  file/logs:
    path: /logs.json

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging, file/traces]
    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging, file/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file/logs]
