version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  default:
    name: opentelemetry
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    volumes:
      - ./src/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "9090"
    logging: *logging

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 100M
    volumes:
      - ./src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./src/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    logging: *logging

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    command:
      - "--query.base-path=/jaeger/ui"
      - "--prometheus.server-url=http://prometheus:9090"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "4317"          # OTLP gRPC default port
      - "16686:16686"   # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    depends_on:
      - prometheus
    logging: *logging

  otelcol:
    image: otel/opentelemetry-collector-contrib
    container_name: otelcol
    command:
      - "--config=/etc/otelcol.yaml"
    volumes:
      - ./src/otelcol/otelcol.yaml:/etc/otelcol.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4317"   # OTLP http receiver
      - "9464"        # Prometheus exporter
    depends_on:
      - jaeger
    logging: *logging
