version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    volumes:
      - ./src/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "9090"

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://prometheus:9090"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "4317"                          # OTLP gRPC default port
      - "16686"                         # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus

  otelcollector:
    image: otel/opentelemetry-collector-contrib
    container_name: otelcollector
    command:
      - "--config=/etc/otelcollector.yaml"
    volumes:
      - ./src/otelcollector/otelcollector.yaml:/etc/otelcollector.yaml
    ports:
      - "4317"          # OTLP gRPC receiver
      - "4318"          # OTLP http receiver
      - "9464"          # Prometheus exporter
    depends_on:
      - jaeger