x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "${MAX_LOG_FILE_SIZE}"
    max-file: "${MAX_LOG_FILE_COUNT}"
    tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:${OTEL_VERSION}
    restart: on-failure
    command:
      - "--config=/etc/otelcollector.yaml"
    volumes:
      - ./src/otelcollector/otelcollector.yaml:/etc/otelcollector.yaml
    ports:
      - ${OTEL_GRPC_PORT}:4317 # OTLP gRPC receiver
      - ${OTEL_HTTP_PORT}:4318 # OTLP http receiver
      - ${OTEL_ZPAGES_PORT}:55679 # zpages (http://localhost:55679/debug/servicez, http://localhost:55679/debug/tracez)
    environment:
      - GOMAXPROCS=${GOMAXPROCS}
      - GOMEMLIMIT=${GOMEMLIMIT}
      - PROMETHEUS_SCRAPE_TARGETS=${PROMETHEUS_SCRAPE_TARGETS}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEM_LIMIT}
    depends_on:
      elasticsearch:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    logging: *logging
